site_name: TAN7's Docs
nav:
  - Home: Home/index.md
  - Mkdocs:
    - build: Mkdocs/基于MKdocs搭建个人wiki.md
  - Wheel-Legged-Robot:
    - The basics: Wheel-Legged-Robot/The basics/plans and records.md
  - RM-Electric Control:

theme:
  name: 'material'

